### ISSUE TITLE
Automate the publishing of milestones and releases as much as possible.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#24]
It's very manual and error prone (forget to push tags, promote to maven central, etc...).

Spring-Data follows a similar release train and memory serves @olivergierke has some automation. Oliver can you point me to it?

**Comment by olivergierke** [comment]
https://github.com/spring-projects/spring-data-dev-tools/tree/master/release-tools

Always WIP. Currently does the following:

1. Defines content of release trains (see `ReleaseTrain`) the modules (i.e. project + version) contained in them, the projects alongside their bug trackers and repositories.
2. `release prepare $trainName $iteration` (with iteration being M1, RC1, GA, SR1..6) — Checks out all Git repos. Creates changelogs from querying the issue trackers. Updates Docbook includes (obsolete now). Updates Maven POMs (the BOM pom, refer to the parent pom in release version, refer to Spring Data Commons in the about to be released version, switch from snapshot to release/milestone repository depending on release iteration). Updates `gradle.properties` for Gradle projects. Commits all changes using author defined in `application-local.properties` (gitignored).
3. You push modules individually to release them via Artifactory. Commons needs to be released before downstream modules can be pushed as they locally already refer to the released version. (To be automated)
4. `release conclude $trainName $iteration` — Pulls latest changes. Finds release commit to manually tag it. Resets parent and Commons dependencies to new snapshot versions. Switches to snapshot repositories again.
5. `release distribute $trainName $iteration` — Checks out release tags. Triggers `mvn clean deploy -Pdistribute` (special Maven profile to build documentation, package JavaDoc etc. and eventually uploads static resources) for Maven projects (static resources for Gradle projects are handled by the release build already, which is why they take so long *sigh*).

There are a few helper commands in there as well that are used during the execution of the release commands but come in handy some times like querying the JIRA for all tickets solved by a release, Checking out release trains etc.

Not sure in how far it would make sense to try to extract the commonly reusable parts and introduce a layer of indirection to cater the different needs imposed by the probably very different setups of the builds?

**Comment by spencergibb** [comment]
@olivergierke is that project private?
