### ISSUE TITLE
Move spring cloud to slf4j

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#39]
I prefer the logging placeholders `{}` and deferred string construction. Since it is part of all spring boot loggers, there is no need worry about not having the `slf4j-api` dependency.

**Comment by spencergibb** [comment]
@dsyer @marcingrzejszczak @adriancole @markfisher @markpollack @mbogoevici @philwebb

**Comment by philwebb** [comment]
It's not technically required for Spring Boot, although most people do end up with it if they use `spring-boot-starter-logging`. The only hard logging requirement we have is a `commons-logging` API.

We've discussed this in the past on the Spring Framework team and decided to stick with commons logging since it has such a stable API and rarely breaks back compatibility. We decided to take the pain of not having `{}` placeholders.

**Comment by spencergibb** [comment]
Ah, so the starters include it, but if they didn't include the starters we wouldn't be guaranteed slf4j.
