### ISSUE TITLE
Release deploys slightly different artifacts to libs-release-local and maven central

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#50]
Current steps are:
```
$ ./mvnw deploy

# later

$ ./mvnw deploy -Pcentral
```
See slack discussion
https://pivotal.slack.com/archives/spring-cloud/p1487362868006845

Possible workaround:
http://stackoverflow.com/questions/635154/multiple-deployments-in-maven#answer-1259799

**Comment by spencergibb** [comment]
IIRC, metadata (times?) changes, therefore jar change, therefore signatures change.

**Comment by gregturn** [comment]
This blog article illustrates what would be quite ugly: http://techtraits.com/build%20management/maven/2012/06/24/Maven-Deploying-multiple-artifacts-from-one-build.html

Essentially, if you manually specify EVERY file (signature files included), then you might be able to upload everything where you wish.

**Comment by mbogoevici** [comment]
`./mvnw deploy` depends on `install`, which effectively rebuilds the jar. While this should in theory detect no changes due to the first `deploy` step, sometimes the plugin decides to recompile the sources, even if they're not changed - e.g. courtesy of this bug https://issues.apache.org/jira/browse/MCOMPILER-205 . There's no intrinsic guarantee that a recompilation and JAR rebuild will not happen.

It shouldn't be necessary to deploy artifacts in two places, though.

One proposal I've made in the past (and I believe @rwinch and @trevormarshall were experimenting with that as well, independently) would be to deploy releases directly to Maven Central and mirror them in Spring repositories. Snapshots and milestones would only be deployed directly to Spring snapshot and milestone repos.

**Comment by spencergibb** [comment]
@mbogoevici thanks for details I couldn't remember.

> deploy releases directly to Maven Central and mirror them in Spring repositories

would be great.

**Comment by mp911de** [comment]
How about taking the Spring Framework route? Publishing artifacts to repo.spring.io, promote artifacts in a second step to Maven Central: https://github.com/spring-projects/spring-framework/wiki/Gradle-build-and-release-FAQ#what-about-publishing-artifacts-to-maven-central

I think this approach requires the release to be built with a CI with the according plugin to support artifact/build promotion.

**Comment by spencergibb** [comment]
That is what we were avoiding

**Comment by spencergibb** [comment]
deploying directly to maven central then letting sync to repo.spring.io
